version: 2.1
jobs:
  save_hello_world_output:
    docker:
    - image: circleci/node:13.8.0
    working_directory: /tmp
    steps:
    - run:
        command: mkdir -p workspace
    - run:
        name: Saving hello world to file
        command: echo Hello world > workspace/output.txt
    - persist_to_workspace:
        root: workspace
        paths:
        - output.txt
  print_output_file:
    docker:
    - image: circleci/node:13.8.0
    working_directory: /tmp
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Say world
        command: cat /tmp/workspace/output.txt`
  print_workflow_id:
    docker:
    - image: circleci/node:13.8.0
    working_directory: /tmp
    steps:
    - run:
        command: echo $CIRCLE_WORKFLOW_ID
workflows:
  longtony:
    jobs:
    - save_hello_world_output
    - print_output_file:
        requires:
        - save_hello_world_output
    - print_workflow_id
  version: 2.1